Try to avoid using GitHub hosted pycodestyle
`pip install flake8` installed pycodestyle-2.9.1, but flake8 fails to
run because it picks up pycodestyle 2.6.0 from GitHub hosted Python:

>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/plugins/pycodestyle.py", line 24, in <module>
>     from pycodestyle import missing_whitespace_after_keyword as _missing_whitespace_after_keyword  # noqa: E501
> ImportError: cannot import name 'missing_whitespace_after_keyword' from 'pycodestyle' (/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pycodestyle.py)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/bin/flake8", line 8, in <module>
>     sys.exit(main())
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
>     app.run(argv)
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/main/application.py", line 336, in run
>     self._run(argv)
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/main/application.py", line 324, in _run
>     self.initialize(argv)
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/main/application.py", line 302, in initialize
>     self.find_plugins(
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/main/application.py", line 128, in find_plugins
>     self.plugins = finder.load_plugins(raw, opts)
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/plugins/finder.py", line 370, in load_plugins
>     return _classify_plugins(_import_plugins(plugins, opts), opts)
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/plugins/finder.py", line 312, in _import_plugins
>     return [_load_plugin(p) for p in plugins]
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/plugins/finder.py", line 312, in <listcomp>
>     return [_load_plugin(p) for p in plugins]
>   File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/flake8/plugins/finder.py", line 298, in _load_plugin
>     raise FailedToLoadPlugin(plugin.package, e)
> flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle" due to cannot import name 'missing_whitespace_after_keyword' from 'pycodestyle' (/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pycodestyle.py).
> ##[error]Process completed with exit code 1.